version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: x
      POSTGRES_PASSWORD: x
      POSTGRES_DB: x
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  crud-service:
    build:
      context: CRUD-Service
      dockerfile: Dockerfile
    ports:
      - 8080-8081:8080
    depends_on:
      - postgres
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:9000
    depends_on:
      - crud-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
